version: '3.4'

services:
  ordermicroservice:
    image: ${DOCKER_REGISTRY-}ordermicroservice
    build:
      context: .
      dockerfile: OrderMicroservice/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - DB_CONNECTION_STRING=Server=192.168.1.29,1432;Database=OrderDB;User Id=sa;Password=Barisaltun508*;Trusted_Connection=False;MultipleActiveResultSets=true
    ports:
      - "5101:80"
    depends_on: 
        - db
        - rabbitmq
  
  paymentmicroservice:
    image: ${DOCKER_REGISTRY-}paymentmicroservice
    build:
      context: .
      dockerfile: PaymentMicroservice/Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
     - DB_CONNECTION_STRING=Server=192.168.1.29,1432;Database=PaymentDB;User Id=sa;Password=Barisaltun508*;Trusted_Connection=False;MultipleActiveResultSets=true
    ports:
      - "5102:80"
    depends_on: 
        - db
        - rabbitmq 

  db:
     image: "mcr.microsoft.com/mssql/server:2019-latest"
     environment:
       SA_PASSWORD: "Barisaltun508*"
       ACCEPT_EULA: "Y"
       ports: "1432:1433"
       #MSSQL_PID: <Developer> 

  rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: "guest"
            RABBITMQ_DEFAULT_PASS: "guest"
        ports:
            - 5672:5672
            - 15672:15672

